### PR TITLE
Import tests from yash project

### PR DESCRIPTION
**Pull request by siteshwar**
These tests were originally written by @magicant for yash project. We
are going to build on top of them.

### CODE REVIEW

**Comment by siteshwar** [comment]
@magicant @kdudka @krader1961 @mirabilos I would appreciate your reviews before merging this.

Currently these tests don't pass for all shells, but we will have to review such tests individually and either fix the tests or respective shells.

**Comment by krader1961** [comment]
I'm not going to review and comment on the style or substance of the tests since this is the first commit and we want it to be identical to the source we're forking.

Should the *README.md* have a paragraph about where this originated and the email with the original author about forking the tests? Other than that I have no objections to merging this to form a starting point.

**Comment by krader1961** [comment]
I'm surprised at the huge number of test failures. But a huge number are either `standard error mismatch` or `standard out mismatch` which suggests reliance on specific wording or formatting of output not mandated by POSIX. One of the first things that will be needed is to modify these tests to included the expected and actual strings like I did for the ksh tests.

**Comment by krader1961** [comment]
There are also quite a few instances of this error when I run this change with ksh on my macOS server:

```
.: cannot execute command `../checkfg': No such file or directory
```

Is this commit missing a file or does the test runner simply need to be modified to suppress that error if the file is optional?

**Comment by magicant** [comment]
The diffs of expected & actual strings are in the `*.trs` file. I did not want to clutter the terminal with so many diffs.

----

`checkfg` is a tiny tool that comes with the original yash test suite that ensures the test is run in a foreground process group. Maybe we can just omit the check (as long as we run the test in foreground.)

**Comment by siteshwar** [comment]
> Should the README.md have a paragraph about where this originated and the email with the original author about forking the tests? Other than that I have no objections to merging this to form a starting point.

I added a credits section to readme file.

**Pull request merged**
